ALTER TABLE donations MODIFY COLUMN co_op ENUM('S4L', 'STUDIO-MATIC', 'STUDIO_MATIC') NOT NULL;
UPDATE donations SET co_op = 'STUDIO-MATIC' WHERE co_op = 'STUDIO_MATIC';
ALTER TABLE donations MODIFY COLUMN co_op ENUM('S4L', 'STUDIO-MATIC') NOT NULL;
